// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"project_id/internal/graphql/scalar"
)

type Account struct {
	ID            string            `json:"id"`
	Username      string            `json:"username"`
	Email         string            `json:"email"`
	Nickname      string            `json:"nickname"`
	Status        int               `json:"status"`
	LastLoginIP   string            `json:"lastLoginIp"`
	LastLoginTime *scalar.Timestamp `json:"lastLoginTime,omitempty"`
	CreatedTime   scalar.Timestamp  `json:"createdTime"`
	UpdatedTime   scalar.Timestamp  `json:"updatedTime"`
}

type AccountDetail struct {
	Account *Account `json:"account"`
	Org     *Org     `json:"org,omitempty"`
}

type Health struct {
	Available bool   `json:"available"`
	Name      string `json:"name"`
	Version   string `json:"version"`
	Env       string `json:"env"`
}

type Org struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	IsDefault   bool             `json:"isDefault"`
	CreatedTime scalar.Timestamp `json:"createdTime"`
	UpdatedTime scalar.Timestamp `json:"updatedTime"`
}

type Query struct {
}
